version: "3.4"

services:
  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - 3000:80
  test:
    build:
      dockerfile: Dockerfile
      context: ./poc/debug
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
      - 9229:9229
    command: yarn nodemon --inspect=0.0.0.0:9229 --signal SIGINT --nolazy app.ts