/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * this is a JSON SChema test for typescript conversion
 */
export interface Booktpoc {
  id: string;
  name: string;
  info: Contact;
}
export interface Contact {
  id: string;
  phone: number;
}
